sub123_mass_rec: "$m_{top}^{rec}$ (GeV)"
sub123_pt_rec: "$p_{T, top}^{rec}$ (GeV)"
w_mass_rec: "$m_{W}^{rec}$ (GeV)"
w_pt_rec: "$p_{T, W}^{rec}$ (GeV)"
mass: "$m_{top}^{true}$"
sim_mass: "$m_{top}^{true}$"
bw_mass: "$m_{top}^{true}$"
jec: "$\\nu_{jec}$"
mu_ttbar: "$\\mu_{t\\bar{t}}$"
gen_pt_shift: "$\\nu_{p_{T}^{t\\bar{t}}}$"
lumi: "$\\nu_{lumi}$"
cor: "$\\nu_{cor}$"
ttbar: "$t\\bar{t}$"
other: "Bkg"
CombinedSubJets_mass: "$m_{top}^{rec}$ (GeV)"
CombinedSubJets_pt: "$p_{T, top}^{rec}$ (GeV)"
SubJet1_mass: "$m_{W}^{rec}$ (GeV)"
SubJet1_pt: "$p_{T, W}^{rec}$ (GeV)"
run2: "Run 2"
run3: "Run 3"
FatJet_tau21: "$\\tau_{21}^{AK8}$"
SubJet1_tau21: "$\\tau_{21}^{AK8,S1}$"
SubJet2_btagDeepB: "b tagging score (AK8, S2)"