name: innfer_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - configargparse=1.7=pyhd8ed1ab_0
  - htcondor-classads=23.6.2=h52b5a28_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=22_linux64_openblas
  - libboost-python=1.84.0=py311h5510f57_3
  - libcblas=3.9.0=22_linux64_openblas
  - libcondor_utils=23.6.2=he4d4b1b_0
  - libcurl=8.8.0=hca28451_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_9
  - libgfortran-ng=13.2.0=h69a702a_9
  - libgfortran5=13.2.0=h3d2ce59_9
  - libgomp=13.2.0=h77fa898_9
  - liblapack=3.9.0=22_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_9
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - munge=0.5.13=h1c5bbd1_1
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py311h64a7726_0
  - openssl=3.3.1=h4ab18f5_0
  - pcre2=10.43=hcad00b1_0
  - pip=24.0=py311h06a4308_0
  - python=3.11.8=hab00c5b_0_cpython
  - python-htcondor=23.6.2=py311hdf31985_0
  - python_abi=3.11=4_cp311
  - readline=8.2=h5eee18b_0
  - scitokens-cpp=1.0.2=haea88ab_0
  - setuptools=69.5.1=py311h06a4308_0
  - snakemake-executor-plugin-cluster-generic=1.0.9=pyhdfd78af_0
  - snakemake-interface-common=1.17.2=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.1.1=pyhdfd78af_0
  - sqlite=3.45.3=h5eee18b_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - aesara==2.9.3
      - alembic==1.13.2
      - appdirs==1.4.4
      - arrow==1.3.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - awkward==2.6.4
      - awkward-cpp==33
      - bayesflow==1.1.6
      - binaryornot==0.4.4
      - cachetools==5.3.3
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - conda-inject==1.3.1
      - connection-pool==0.0.3
      - cons==0.4.6
      - contourpy==1.2.1
      - cookiecutter==2.6.0
      - cramjam==2.8.3
      - cycler==0.12.1
      - datrie==0.8.2
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docutils==0.21.2
      - dpath==2.1.6
      - etuples==0.3.9
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fsspec==2024.5.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.64.0
      - h5py==3.11.0
      - hep-ml==0.7.2
      - humanfriendly==10.0
      - idna==3.7
      - immutables==0.20
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - logical-unification==0.4.6
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - minikanren==1.0.3
      - ml-dtypes==0.3.2
      - mplhep==0.3.48
      - mplhep-data==0.0.3
      - multipledispatch==1.0.0
      - nbformat==5.10.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optuna==3.6.1
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - plac==1.4.3
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - prettytable==3.10.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pulp==2.8.0
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyfiglet==1.0.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytest==8.2.1
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - random-word==1.0.11
      - referencing==0.35.1
      - requests==2.32.1
      - requests-oauthlib==2.0.0
      - reretry==0.11.8
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==2.2.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - snakemake==8.11.6
      - snakemake-interface-report-plugins==1.0.0
      - snakemake-interface-storage-plugins==3.2.2
      - sqlalchemy==2.0.31
      - stopit==1.1.2
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-probability==0.23.0
      - termcolor==2.4.0
      - text-unidecode==1.3
      - theano==1.0.5
      - threadpoolctl==3.5.0
      - toolz==0.12.1
      - toposort==1.10
      - tqdm==4.66.4
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uhi==0.4.0
      - uproot==5.3.7
      - urllib3==2.2.1
      - wandb==0.17.0
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - wrapt==1.14.1
      - xgboost==2.0.3
      - yte==1.5.4
      - zipp==3.18.2
prefix: /vols/cms/gu18/innfer_v1/miniconda/files/envs/innfer_env
