## Load data
#- step: "LoadData"
#  submit: "configs/submit/condor_4_cpus.yaml"

# Preprocess data
- step: "PreProcessParallelInitial"
  submit: "configs/submit/condor_gpu.yaml"
- step: "PreProcessParallelModel"
  submit: "configs/submit/condor_gpu.yaml"
  run_options:
    points_per_job: 4
- step: "PreProcessParallelValidation"
  submit: "configs/submit/condor_gpu.yaml"
  run_options:
    points_per_job: 4
- step: "PreProcessParallelNuisanceVariations"
  submit: "configs/submit/condor_gpu.yaml"
  run_options:
    points_per_job: 4
- step: "PreProcessParallelMerge"
  submit: "configs/submit/condor.yaml"